package org.xiangbalao.grenndao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.xiangbalao.grenndao.model.Test;
import org.xiangbalao.grenndao.model.Order;
import org.xiangbalao.grenndao.model.GeneraOrder;

import org.xiangbalao.grenndao.dao.TestDao;
import org.xiangbalao.grenndao.dao.OrderDao;
import org.xiangbalao.grenndao.dao.GeneraOrderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig generaOrderDaoConfig;

    private final TestDao testDao;
    private final OrderDao orderDao;
    private final GeneraOrderDao generaOrderDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testDaoConfig = daoConfigMap.get(TestDao.class).clone();
        testDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        generaOrderDaoConfig = daoConfigMap.get(GeneraOrderDao.class).clone();
        generaOrderDaoConfig.initIdentityScope(type);

        testDao = new TestDao(testDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        generaOrderDao = new GeneraOrderDao(generaOrderDaoConfig, this);

        registerDao(Test.class, testDao);
        registerDao(Order.class, orderDao);
        registerDao(GeneraOrder.class, generaOrderDao);
    }
    
    public void clear() {
        testDaoConfig.clearIdentityScope();
        orderDaoConfig.clearIdentityScope();
        generaOrderDaoConfig.clearIdentityScope();
    }

    public TestDao getTestDao() {
        return testDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public GeneraOrderDao getGeneraOrderDao() {
        return generaOrderDao;
    }

}
